name: melos_tester
repository: https://github.com/rly-kim/melos_tester
packages:
  - packages/**

command:
  # versioning은 pub.dev용으로만 동작. private package(publish_to: none)들은 skip된다.
  version:
    branch: main # only allow versioning to happen on main branch
    linkToCommits: true
    workspaceChangelog: true
  bootstrap:
    runPubGetInParallel: true
    environment:
      sdk: '>=3.2.5 <4.0.0'
      flutter: '>=3.3.0'
    dependencies:
      # bootstrap 실행하면, 이 공통 버전을 resolve 된 버전으로 맞춰주네..
      plugin_platform_interface: 2.1.1
      flutter_bloc: 7.3.3

scripts:
#  build:
#    exec: flutter pub run build_runner build --delete-conflicting-outputs
#    select-package:
#      depends-on: build_runner
  postclean:
    run: melos run clean:flutter --no-select
    description: Runs "flutter clean" in all Flutter packages
  clean:flutter:
    run: melos exec -c 4 --fail-fast -- "flutter clean"
    description: Run Flutter clean for a specific package in this project.
    packageFilters:
      flutter: true
ignore:
  # e.g. ignore example apps
  - "packages/**/example"
