name: photo_retriever_plugin
description: "photo retriever plugin interface for flutter"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
#  photo_retriever_platform_interface:
#    git:
#      url: https://github.com/rly-kim/melos_tester.git
#      ref: main
#      path: packages/flutter_photo_retriever/photo_retriever_platform_interface
#  photo_retriever_ios:
#    git:
#      url: https://github.com/rly-kim/melos_tester.git
#      ref: main
#      path: packages/flutter_photo_retriever/photo_retriever_ios

  photo_retriever_platform_interface:
    path: ../photo_retriever_platform_interface
  photo_retriever_ios:
    path: ../photo_retriever_ios
  plugin_platform_interface: 2.1.1 # todo delete

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      ios:
        default_package: photo_retriever_ios
